# Site settings
title: Abhinav's Blog
header-img: img/nyc.jpg
email: abhinav.kurada@columbia.edu
copyright_name: Abhinav Kurada
description: "Abhinav Kurada | I am an incoming Egleston Scholar at Columbia University."
url: "http://akurada.tech"
# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/blog"
twitter_username: abhinavkurada
github_username:  akurada
facebook_username:  abhinav.kurada
email_username:  abhinav.kurada@columbia.edu
linkedin_username: abhinavkurada

logo: /img/circular.png

image:
  twitter: /img/nyc.jpg
  facebook: /img/nyc.jpg
  height: 100
  width: 100

author:
  twitter: abhinavkurada
  
  facebook: 
    app_id: 1822670604630103
    publisher: 1822670604630103
    admins: 1822670604630103
# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: e86f974d8e6e5c39

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","LICENSE","CNAME"]

gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap, jekyll-seo-tag]

sass:
  style: :compressed # You might prefer to minify using :compressed

